sudo: required

services:
  - docker

language: php
php:
#  - 5.4
#  - 5.5
  - 5.6
#  - 7

env:
  global:
    - CORE_BRANCH=master
    - APP_NAME=files_primary_swift
  matrix:
    - DB=sqlite

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

before_install:
  - composer install
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
  - cd ../core
  - php occ app:enable files_primary_swift

  # Start ceph
  - export DEBUG=on
  - bash apps/files_primary_swift/tests/env/start-swift-ceph.sh
  - cp apps/files_primary_swift/tests/swift.config.php config/autotest-storage-swift.config.php
  #- cp apps/objectstore/tests/env/autotest.sh autotest.sh
  - echo "memory_limit=2048M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # delete swift tests
  - rm -rf tests/lib/Files/ObjectStore/SwiftTest.php
before_script:
  - phpenv config-rm xdebug.ini || true

script:
  # Run phpunit tests
  - NOCOVERAGE=1 RUN_OBJECTSTORE_TESTS=1 make test-php TEST_DATABASE=$DB

after_script:
  - cat /dev/shm/data-autotest/owncloud.log

matrix:
#  include:
#    - php: 5.4
#      env: DB=mysql
#    - php: 5.4
#      env: DB=pgsql
#    - php: 5.4
#      env: DB=oracle
  include:
    - php: 7.0
      env: DB=mysql
  allow_failures:
    - php: hhvm
  fast_finish: true
