sudo: required

services:
  - docker

language: php
php:
#  - 5.4
#  - 5.5
  - 5.6
#  - 7

env:
  global:
    - CORE_BRANCH=master
  matrix:
    - DB=sqlite

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

before_install:
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh files_primary_swift $CORE_BRANCH $DB
  - cd ../core
  - php occ app:enable files_primary_swift

script:
  # Run phpunit tests
  - NOCOVERAGE=1 RUN_OBJECTSTORE_TESTS=1 PRIMARY_STORAGE_CONFIG="swift" ./autotest.sh sqlite

matrix:
#  include:
#    - php: 5.4
#      env: DB=mysql
#    - php: 5.4
#      env: DB=pgsql
#    - php: 5.4
#      env: DB=oracle
  allow_failures:
    - php: hhvm
  fast_finish: true
